const REFRESH_MS = {
  brazilStats: 5 * 60 * 1000,  // BCB series update at most daily; 5 min is plenty
  news: 3 * 60 * 1000,         // headlines, refresh every 3 min
  futuresBoard: 2 * 60 * 1000, // data/quotes.json is regenerated by GitHub Actions every ~10 min
  usMacro: 30 * 60 * 1000      // FRED series (monthly CPI, daily Fed Funds) barely move intraday
};

function updateClock() {
  const now = new Date();
  document.getElementById("clock").textContent = now.toLocaleTimeString("pt-BR", { hour12: false }) + " (hora local)";
}

function setStatus(ok) {
  const dot = document.getElementById("statusDot");
  const text = document.getElementById("statusText");
  dot.classList.remove("ok", "err");
  dot.classList.add(ok ? "ok" : "err");
  text.textContent = ok ? "dados atualizados" : "falha parcial ao atualizar";
}

async function refreshAll() {
  const ok = await refreshBrazilStats();
  await refreshNews();
  setStatus(ok);
}

document.addEventListener("DOMContentLoaded", () => {
  mountAllWidgets();

  updateClock();
  setInterval(updateClock, 1000);

  refreshAll();
  refreshFuturesBoard();
  refreshUsMacro();
  setInterval(refreshBrazilStats, REFRESH_MS.brazilStats);
  setInterval(refreshNews, REFRESH_MS.news);
  setInterval(refreshFuturesBoard, REFRESH_MS.futuresBoard);
  setInterval(refreshUsMacro, REFRESH_MS.usMacro);
  setInterval(updateFuturesMeta, 1000);
});
